### ISSUE TITLE
Feature "Шаблоны" - сохранения/загрузки записей в shared репозитории 

### ISSUE THREAD

**Issue by programp** [donvadicastro/case-management#14]
Выделено отсюда - #7, тк это был issue про "пролемку" отображения project/usecase/entity/... 
Данная тема родилась там, но теперь живет здесь. Речь о втором этапе организации работы с проектами, а именно:
- добавить возможность глобального и локального репозитория use cases, actors, actions, entities+properties, queries, functions, чтобы можно было использовать  как shared, так и project-specific

**Comment by programp** [comment]
Например, можно сделать так:

1. В отдельном контроле формы создания/редактирования любого элемента модели (будь-то actor, use case, entity, ...) , иметь возможность указать/выбрать название репозитория из списка репозиториев, в который сохранять элемент модели и
2. При заполнении полей формы иметь возможность:
- выбирать репозиторий шаблонных элементов, а затем
- выбирать из него конкретный shared шаблон для авто-заполнения полей формы шаблонными данными;

Это увеличило бы скорость моделирования в разы из-за того, что моделировать будет помогать гибкая, структурированная система шаблонов, а не просто один общий shared-реопзиторий.

**Comment by programp** [comment]
Просто предположу, чего нам такой, более крутой вариант будет стоить:

- на формах редактирования элементов модели появятся доп. контролы для загрузки полей формы шаблонными данными, сохраненными ранее:
  - контрол для выбора шаблонного репозитория из списка;
  - контрол для выбора шаблонного элемента из выбранного до этого шаблонного репозитория;
- на формах редактирования элементов модели появятся доп. контролы для сохранения данных формы как шаблона (заполняются только при необходимости сохранить в шаблон) в один из шаблонных репозиториев: 
  - контрол для выбора шаблонного репозитория из списка;
  - контрол для выбора шаблонного элемента из выбранного до этого шаблонного репозитория для перезаписи (по определению должен стоять) или для простого указания нового/другого (не такого как поле name элемента) имени шаблона.
- сущность Repository со свойством, указываюшим на тип репозитория, согласующегося с типом элемента модели (actor, action, use case, entity и тп.).

**Comment by programp** [comment]
> Просто предположу, чего нам такой, более крутой вариант будет стоить:
> 
> * на формах редактирования элементов модели появятся доп. контролы для загрузки полей формы шаблонными данными, сохраненными ранее:
>   
>   * контрол для выбора шаблонного репозитория из списка;
>   * контрол для выбора шаблонного элемента из выбранного до этого шаблонного репозитория;
> * на формах редактирования элементов модели появятся доп. контролы для сохранения данных формы как шаблона (заполняются только при необходимости сохранить в шаблон) в один из шаблонных репозиториев:
>   
>   * контрол для выбора шаблонного репозитория из списка;
>   * контрол для выбора шаблонного элемента из выбранного до этого шаблонного репозитория для перезаписи (по определению должен стоять) или для простого указания нового/другого (не такого как поле name элемента) имени шаблона.
> * сущность Repository со свойством, указываюшим на тип репозитория, согласующегося с типом элемента модели (actor, action, use case, entity и тп.).

С точки зрения модели, это можно реализовать, добавив в сущность каждого из элементов модели свойство-рефку на один из соответствующих репозиториев. Например, какой-то конкретный Use Case теперь будет иметь рефку на репозиторий UC_SharedRepository_1, который может быть одним из нескольких (UC_SharedRepository_1, UC_SharedRepository_2, ...). Для каждого типа элемента модели (actor, action, use case, entity и тп.) будут свои репозитории. 
Создавать и редактировать репозитории нужно будет отдельно, чтобы не засорять диалоговые формы элементов. Возможностью перехода из шаблонного репозитория на редактирование выбранного шаблонного элемента, входящего в репозиторий, - тоже будет очень удобно.

**Comment by donvadicastro** [comment]
Выношу из текущего майлстона взамено https://github.com/donvadicastro/case-management/issues/22

**Comment by programp** [comment]
> Выношу из текущего майлстона взамено #22

Я не совсем понимаю смысл замены этой задачи на уже автоматически выпоненную #22 (в данный момент сущности уже есть project-scoped). То есть эта задача остается. В этом майлстоне или в другом - вопрос пока вторичный. В конце концов, майлстоны мы определяем сами. 

Критического значения задача не имеет - согласен, но если не в бете, так в альфе, если не в альфе, то в релизе, если не врелизе, то в 1.01, но ее нужно будет сделать.

И вот вопрос того, насколько быстро ее можно реализовать влияет на то, как далеко ее откладывать. Как мне видится решения я здесь уже описал выше и доописал [тут](https://github.com/donvadicastro/case-management/discussions/21), в дискуссиях.

С реализацией контроллов для загрузки из репозитория и записи в репозиторий - с этим можно повременить и поиграться с тем, как это сделать. Но...

Как по мне, то внедрение самой модели репозиториев и привязки к ним ресурсов - плевое дело:
- доп поле-рефка в объекте ресурса (Actor, Action, UseCase, Entity | Query | Function, ...), 
  содержащая референс на запись репозитория в таблице Repository;
- таблица репозиториев Repository
  - id
  - type (_repotype.actor, repotype.action, repotype.usecase, repotype.entity, repotype.query, repotype.function_)
  - name
 
Довольно просто и юзабельно, можно быстро реализовать. В чем я ошибаюсь?

**Comment by donvadicastro** [comment]
1) Темплейты - проект специального типа, определяется просто флагом при создании проекта
![image](https://user-images.githubusercontent.com/8946681/143570029-1e29ea9e-6e6d-45bb-8f55-70dc65a8ed7f.png)

2) Все что создано в границах этого проекта тоже является shared ресурсами

3) Любой проект может имортировать весь контент из темплейта - в этом случае все ресурсы созданные в контексте шаблонного проекта будут реплицированы в проекте, в который они импортируются
![image](https://user-images.githubusercontent.com/8946681/143570473-c1668b90-f432-4dc3-90ea-01fd6f22cb64.png)

4) оба типа проектов доступны из одной страницы - разделены лишь на секции
![image](https://user-images.githubusercontent.com/8946681/143570907-54e56981-67e5-450e-a4fb-8b3c515731e2.png)
