### ISSUE TITLE
Дерево юзкейсов

### ISSUE THREAD

**Issue by JarekGazlowe** [donvadicastro/case-management#2]
2) должна быть видна структура деревом юзкейсов которые вносятся внутрь каждого проджекта. Если, например, мне хочется вбить юзкейс для игрока, который должен перемещаться по карте, я должен зайти в сущности->игрок—>действия игрока и там добавить (это пример)

**Comment by donvadicastro** [comment]
Правильно я понимаю, что это вопрос минус одной выпадашки на форме юз-кейсов только? Дополнительное удобство, но не ограничение. Или я неправильно понял требование?

**Comment by JarekGazlowe** [comment]
![image](https://user-images.githubusercontent.com/94170525/141643336-451774d6-8a5a-4060-8954-f0d4b62d2757.png)

должно отображаться деревом вот так

![image](https://user-images.githubusercontent.com/94170525/141643374-258c1159-c627-4f4a-b410-10a6f530475c.png)

**Comment by donvadicastro** [comment]
Юз-кейс потенциально не может иметь иерархию, ведь это атомарное требование. Возможно это какой-то другой тип сущности, которая представлена деревом?

**Comment by JarekGazlowe** [comment]
Я выше топик создал, в списке топиков. Для получения полноценного дерева, нужно формировать "отношения"

**Comment by donvadicastro** [comment]
![image](https://user-images.githubusercontent.com/8946681/141648139-7725fc30-c594-4afd-86b9-7603eee42e16.png)

Сейчас добавлена страница дашборда, где проэкты и юз-кейсы собраны вместе. Насколько важна именно иэрархия? Или это просто вопрос отображения всего на одной странце?

**Comment by JarekGazlowe** [comment]
Иерархия важна для создания дерева (насколько я могу понять). Без структурирования, ты не сможешь забрать дерево проекта, а также, например, генерить отчеты "юзкейсы этого эктора" или "юзкейсы с этим энтити"

**Comment by donvadicastro** [comment]
Убрал use-cases элемент меню - теперь нельзя создать рутовые кейсы, они сразу должны быть от проэкта
![image](https://user-images.githubusercontent.com/8946681/141655937-4b437b83-5de5-4add-a078-51bcb7e1ed5d.png)

при навигации в конкретный проэкт добавлены кейсы этого проэкта
![image](https://user-images.githubusercontent.com/8946681/141655966-415f3ded-ae05-4d34-b127-ada5e888c70b.png)

при переходе в существующий кейс или создание нового - проэкт выбирать не надо - он привязывается относительно текущего
![image](https://user-images.githubusercontent.com/8946681/141655992-d109220f-34db-4f4c-b9cf-06b923a168fd.png)

**Comment by programp** [comment]
Рефрешнул страницу - пока изменений не вижу

**Comment by programp** [comment]
> Убрал use-cases элемент меню - теперь нельзя создать рутовые кейсы, они сразу должны быть от проэкта ![image](https://user-images.githubusercontent.com/8946681/141655937-4b437b83-5de5-4add-a078-51bcb7e1ed5d.png)
> 
> при навигации в конкретный проэкт добавлены кейсы этого проэкта ![image](https://user-images.githubusercontent.com/8946681/141655966-415f3ded-ae05-4d34-b127-ada5e888c70b.png)
> 
> при переходе в существующий кейс или создание нового - проэкт выбирать не надо - он привязывается относительно текущего ![image](https://user-images.githubusercontent.com/8946681/141655992-d109220f-34db-4f4c-b9cf-06b923a168fd.png)

я так понял, что это правка к этой ["проблемке"](https://github.com/donvadicastro/case-management/issues/7).
мы с яриком пока не можем ничего попробовать - нигде не работает кнопа submit.

**Comment by donvadicastro** [comment]
Сейчас уже должно быть все нормально

**Comment by programp** [comment]
продолжу по теме данного issue. это хотелка, но важная. 

_чтобы ее начать делать, нужно разобраться со всеми остальными базовыми фичами, которые не все еще полностью и точно реализованы (все, что считал нужным описал в соостветсвутющих issues)._ 

после того, как вся модель будет реализована должным образом, ярик сможет вносить все элементы проекта(-ов) через соответствующие страницы. это базовая функциональность и ее должно хватать. 

ярик же хочет иметь ко всему этому функциональный dashboard, задача которого - удобная навигация по дереву usecase-actor-entity/query/function-action с возможностью добавить usecase в процессе навигации. 

это важно потому, что процесс написания юзкейсов требует время от времени сверяться на предмет того, например, "ничего ли не забыто?". И вот для этого нужно выходить на "поверхность" и смотреть на структуру проекта и его дерево.

**Comment by programp** [comment]
так вот, собственно, то, как это дерево должно выглядеть мы опишем дальше. а это я просто еще раз описал то, что ярик хотел сказать, но, возможно, был не понят.
