### ISSUE TITLE
Формы добавления различных опций в поля выбора (если в списке нет)

### ISSUE THREAD

**Issue by JarekGazlowe** [donvadicastro/case-management#3]
3) справа от форм выбора различных опций, нужно чтобы была кнопка ведущая на страницу создания новой сущности (если никакая из выбранных не подходит)

**Comment by JarekGazlowe** [comment]
![image](https://user-images.githubusercontent.com/94170525/141643521-92798fda-a020-4471-a17c-5e58589b1fde.png)

контролы, которы позволяют ДОБАВИТЬ пункт, который нужно выбирать, не переходя на страничку

**Comment by JarekGazlowe** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/puerh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/puerh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



123 | 3123 | 12315
-- | -- | --
1231451 | 125165 | 1231312



</body>

</html>

**Comment by programp** [comment]
Привожу два варианта того, как можно реализовать данную фичу. 
Допустим, мы в форме создания нового Use Case. Пусть в списке Query нет той записи, которая нужна.
Вместо того, чтобы идти через верххнее меню в раздел Query для создания новой записи (с последующим возвратом), хотелось бы иметь одну из возможностей:
- (в идеале) вставка новой записи прямо в том же выпадающем меню, путем ввода name/title записи;
  - в таком случае новая запись создастся, но без описания деталей (description для actor, action и всего списка остальных полей для entity | query |function), которые потом можно будет добавить перейдя на только что созданную запись в соответствующем ей разделе;
  
  ![image](https://user-images.githubusercontent.com/9744471/142278850-f2e914ce-c01b-4fc2-b9de-d6c32ec0d42a.png)

- (компромисс) элемент "+", нажимая который пользователь перейдет на форму создания новой записи в соответствующем разделе;
  - в таком варианте просто экономится лишнее движение мышкой к верхнему меню.
  
  ![image](https://user-images.githubusercontent.com/9744471/142276713-8e3b8906-f68e-43e4-a13d-a2e772df0a05.png)
