### ISSUE TITLE
У Query должны быть определены поля from, select, where и return type, return default

### ISSUE THREAD

**Issue by programp** [donvadicastro/case-management#5]
https://usecase-management.netlify.app/management/queries/new

![image](https://user-images.githubusercontent.com/9744471/141645103-50908f38-dd8d-491f-919b-54eb47d11b72.png)

**from, select, where**
Описание запроса через понятийную базу sql. Вариант реализации:
from -> выпадающий список, состоящий из всех Entity проекта;
select -> combobox со значением свойств Entity, выбранной во "from"
where -> описание условия в произвольной форме (">= 5", "<3", "больше среднего за месяц")

**return type**
В отличие от Function, где указывается тип возвращаемого функцией значения, у Query тип возвращаемого значения можно определить по трем полям запроса (query.from, query.select, query.where). Если я не ошибаюсь, то это всегда будет список, даже если из одной записи. Однако, можно оставить это поле для потенциальных нужд. При конфликте [from, select, where]
и [return type] предпочтение полностью отдается первому.

**return default**
Дефолтное значение для нужд генерации.

Описываемый запрос в генерируемом коде, сможет выглядеть так:
```
function name () {
   // query.description
   // from: query.from, 
   // select: query.select, 
   // where: query.where
   return query.default
}
```

**Comment by donvadicastro** [comment]
> select -> combobox со значением свойств Entity, выбранной во "from"
не нашел где описываются атрибуты Entity, пока что это просто сущность без описания атрибутов, оставлю просто строковым полем на сейчас для произвольного текста
