### ISSUE TITLE
На проблемку напали (с)

### ISSUE THREAD

**Issue by JarekGazlowe** [donvadicastro/case-management#7]
В связи с тем, что мы имеем "проекты", что подразумевает наличие проектов в количестве более 1, то имеем следующую проблему:

Внутри проекта есть юзкейсы.
Внутри юзкейсов есть акторы, экшны и так далее.

Проблема состоит в том, чтобы записывать принадлежность внутренних пунктов к родительскому проекту или более высокому пункту меню. Это "необходимо" для реализации "дерева" проекта.

Нужно или:
1) делать только один проект за раз (но это не избавляет нас от необходимости добавления отношения между энтити-екшн-актор-юзкейс.
2) либо делать "шаблоны" которые потом добавлять в родительский проект и записывать их принадлежность к этому проекту. И в этом случае "добавление" шаблона будет вести на создание именно шаблона, который потом можно будет "привязать" к родительскому проекту.

Это необходимо обсудить, так как очень критично для проекта.

**Comment by donvadicastro** [comment]
Ты имеешь ввиду иметь actors, entities, queries, functions per project, а не общий список для всех проэктов? В этом основной вопрос?

**Comment by programp** [comment]
`Ты имеешь ввиду иметь actors, entities, queries, functions per project, а не общий список для всех проэктов? В этом основной вопрос?` 

Actors, actions, entities, queries, functions, use cases - уже реализованные, а также entity properties, которых нет еще в реализации (об этом добавил issue) - все это должно быть per project, в большинстве случаев. Теперь о сути "проблемки".
1. Первая часть "проблемки" в том, что пока что только Use Case определен как per project.
2. Вторая часть "проблемки" в том, что то, как процесс задания принадлежности Use Case какому-то Project реализован сейчас (путем задания значения поля "Project" в форме добавления Use Case) - это не самый удобный вариант. И не самый логичный. Если мы так будем указывать принадлежность всех элементов модели к модели какого-то Project, то будет много однотипных действий вместо одного - например, "однозначно задать текущий Project" один раз через интерфейс.

**Comment by programp** [comment]
С одной стороны, любое множество проектов всегда будут иметь много общего: стандартные Actor, Actions, Entity, UseCase и все остальное. В таком случае такой способ, как сейчас, логичен:
- все, кроме Use Case создается не per Project, а как общедоступный для всех Project "шаблон";
- тогда UseCase будет тем, что объединяет выбранное из множества общего шаблонного в проектное частное.

С другой стороны, даже если шаблонного будет много (любой Action типа crud, Actors типа user registered|unregistered и тп), но будет также немало частных случаев, которые будут нужны только в одном проекте, то такие шаблоны (сущность "Trader", например) будут мусором для других проектов (где "Trader" не нужен). В таком случае объединить "всех участников забега" в одном UseCase может оказаться не такой уж легкой задачей из-за того, что выбрать шаблонный элемент среди кучи других будет просто напросто неудобным (огромный выпадающий список на выбор = плохо).

**Comment by donvadicastro** [comment]
Я предлагаю тогда поэтапное расширение:
* на первом этапе управление use-case-ов на уровне проэкта (без необходимости выбирать проэкт, а всегда использовать текущий проэкт), но при этом использовать глобальный репозиторий actors, entities, queries, functions
* на втором этапе добавить возможность глобального и локального репозитория actors, entities, queries, functions, чтобы можно было как использовать shared, так и project-specific

В контексте этой задачи первый пункт только.

**Comment by programp** [comment]
Вадя, не успел прочитать твой коммент, писал свой.
Мысли "Как лучше организовать процесс описания принадлежности элемента модели какому-либо проекту". Варианты:

1. Как сейчас, когда все элементы шаблонные и общедоступны для всех проектов. 
2. Как сейчас, но с возможностью указывать принадлежность любого элемента модели к конкретному "Project", выбираемому из списка проектов, а также указывать флаг "isTemplate", чтобы элемент сохранился также как и общедоступный/шаблонный.
3. Все модели создаются в одном и только одном проекте за раз. Тут проект выбирается единожды так, чтобы все создаваемые элементы модели мапились на выбранный проект автоматически (пока не будет выбран/загружен новый "текущий проект"). В отличие от предыдущего варианта, этот - более эргономичный, т.к. мапить элемент модели на конкретный проект каждый раз не нужно.
4. Как в предыдущем варианте, но с описанной ранее возможностью задания флага "isTemplate" при сохранении элемента модели. Тогда элемент сохранялся бы и как элемент модели текущего проекта (изначально заданного), так и был бы доступен для других проектов.

**Comment by programp** [comment]
> Я предлагаю тогда поэтапное расширение:
> 
> * на первом этапе управление use-case-ов на уровне проэкта (без необходимости выбирать проэкт, а всегда использовать текущий проэкт), но при этом использовать глобальный репозиторий actors, entities, queries, functions
> * на втором этапе добавить возможность глобального и локального репозитория actors, entities, queries, functions, чтобы можно было как использовать shared, так и project-specific
> 
> В контексте этой задачи первый пункт только.

Ну вот описанный мной вариант 4 - это как описанный тобой второй этап, но с конкретным вариантом того, как задать isShared (isTemplate) для элемента модели - через задание флага (условно, radio button). Мне видится это оптимальным, но задание флага isShared (isTemplate) можно реализовать иначе, еще круче, без флага. Например, если:

1. В отдельном контроле формы создания/редактирования любого элемента модели (будь-то actor, use case, entity, ...) , иметь возможность указать/выбрать название репозитория из списка репозиторие, в который сохранять элемент модели и
2. При заполнении полей формы иметь возможность 
- выбирать репозиторий шаблонных элементов, а затем
- выбирать из него конкретный shared шаблон;

то это увеличило бы скорость моделирования в разы из-за того, что моделировать будет помогать гибкая, структурированная система шаблонов, а не просто один общий shared-реопзиторий.

**Comment by programp** [comment]
Просто предположу, чего нам такой, более крутой вариант будет стоить:

- на формах редактирования элементов модели появятся доп. контролы для загрузки полей формы шаблонными данными, сохраненными ранее:
  - контрол для выбора шаблонного репозитория из списка;
  - контрол для выбора шаблонного элемента из выбранного до этого шаблонного репозитория;
- на формах редактирования элементов модели появятся доп. контролы для сохранения данных формы как шаблона (заполняются только при необходимости сохранить в шаблон) в один из шаблонных репозиториев 
  - контрол для выбора шаблонного репозитория из списка;
  - контрол для выбора шаблонного элемента из выбранного до этого шаблонного репозитория для перезаписи (по определению должен стоять) или для простого указания нового/другого (не такого как поле name элемента) имени шаблона.
- сущность Repository с указанием типа репозитория согласующегося с типом элемента модели (actor, action, use case, entity и тп.).

С точки зрения модели, это можно реализовать, добавив в сущность каждого из элементов модели свойство-рефку на один из соответствующих репозиториев. Например, какой-то конкретный Use Case теперь будет иметь рефку на репозиторий UC_SharedRepository_1, который может быть одним из нескольких (UC_SharedRepository_1, UC_SharedRepository_2, ...). Для каждого типа элемента модели (actor, action, use case, entity и тп.) будут свои репозитории. 
Создавать и редактировать репозитории нужно будет отдельно. Возможностью перехода из шаблонного репозитория на редактирование выбранного шаблонного элемента, входящего в репозиторий, - тоже будет очень удобно.
