### ISSUE TITLE
Нужна возможность задавать предустановленные значения (варианты значений) полей форм через перечисления/константы/ограничения

### ISSUE THREAD

**Issue by programp** [donvadicastro/case-management#9]
[Здесь](https://github.com/donvadicastro/case-management/issues/4) [и здесь](https://github.com/donvadicastro/case-management/issues/6) описал два конкретных случая, где данная возможность может быть нужна. Уверен, что это не последние примеры.

Речь идет о возможности задавать то, что является не описанием модели конкретного проекта, а настройками самого "приложения для описания приложений" и его модели, а именно:
1. перечисления вариантов предустановленных значений того или иного свойства сущностей, определяющих проекты;
2. определение констант;
3. ограничений для каких-либо значений.

Для начала пункт 1. Он самый важный. Пункт 2 - не критичен, пока кейса для него конкретного нет, но он может появиться и учитывая, что это усеченный вариант пункта 1 (одно значение, а не перечисление), то его можно реализовать "за компанию". Пункт 3 - опционально, описано с оглядкой на перспективу.

Предлагаю реализовать эту возможность в разделе "Settings".
Задавать такие настройки предлагаю так же, как и все остальные записи (entity, например), по сценарию:
- Заходим в "Settings"
- Выбираем раздел "Preset values"
- Выбираем "Добавить"
- Выбираем с помощью radio-button тип задаваемого "пресета" из трех доступных вариантов ["constant", "enumerator", "constraint"]
- далее, зависимо от предыдущего выбора:
   - для **constant** задаем поля _name_ и _value_;
   - для **enumerator** задаем поле _name_ и поле _value list_ списком (в столбик, например);
   - для **constraint** ничего не предусматривать пока, кроме поля name;
- жмем "Submit"

**Comment by programp** [comment]
Примеры, для которых нужна данная фича:
1. [Отсюда](https://github.com/donvadicastro/case-management/issues/4)
- return type может принимать два значения, которые я вижу на данный момент - это Value и List. 
2. [Отсюда](https://github.com/donvadicastro/case-management/issues/6)
- type задается из вариантов значений: ["string", "number", "calculated", "reference", "key"];

На данный момент: 
- пример 1 я не наблюдаю в ui, а потому могу только показать, что ее нет
![image](https://user-images.githubusercontent.com/9744471/141655247-7967a846-97a8-4597-b3cf-ce918e4903a5.png)
и напомнить про [issue](https://github.com/donvadicastro/case-management/issues/4), в котором я про это написал;
- пример 2 ты захардкодил и выдал через radio-button:
![image](https://user-images.githubusercontent.com/9744471/141655202-f6a76ae4-8e50-4d83-aef6-0cdc554ead15.png)

Если ты захардкодишь и случай из примера 1, то оба примера уже будут реализованы иначе, чем я запросил в данной фиче. Но это не отменяет актуальность фичи как таковой. Это будет более гибко. Но для начала хардкод - вполне.

**Comment by donvadicastro** [comment]
Поскольку у каждого из этого типа потенциально может быть кастом логика привязанная (например при выборе calculated необходимо ввести формулу), а значит может влиять в целом на дата модель (тот же calculated подразумевает, что есть отдельное поле для хранение формулы) то динамический менеджмент этого списка будет очень сложной задачей. Шардкод здесь вижу наибоее оптимальный подход (учитывая что к-во типов лимитированное и лимитированное очень небольшим списком).

**Comment by programp** [comment]
Ну да, пока нет смысла впрягаться в этот вопрос. Пока всего два юзкейса и ты уже их захардкодил... Если что вернемся. 
Закрываю.
